### ISSUE TITLE
Missing Examples from Wiki

### ISSUE THREAD

**Issue by ca-australia-dudley** [mindfulsoftware/myFastway.ApiClient#12]
Sample code which provides examples of how to perform requests once an access_token has been generated.

**Comment by scottbattersby** [comment]
Here's a rough-as-guts example.  

`$headers = array();
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
$headers[] = 'Accept: */*';
$headers[] = 'User-Agent: whatever';
$headers[] = 'Cache-Control: no-cache';
$headers[] = 'Connection: keep-alive';
$headers[] = 'Authorization: Bearer $access_token');
$ch = curl_init("https://api.myfastway.com.au/api/accounts/available/balance");
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$response_body = curl_exec($ch);
curl_close($ch);
unset($ch);
$o = json_decode($response_body);
echo $o->data->available;`

**Comment by ca-australia-dudley** [comment]
'Authorization: Bearer $access_token'
This was the part which wasn't clear for me, is this mentioned somewhere in the wiki?, or was this excluded because it was expected to be found elsewhere when dealing with the technologies used?, Thanks for the reply.

**Comment by scottbattersby** [comment]
Ah yeah I do remember being stuck on that for a while.  I think it's just how OAuth works, so it's assumed knowledge.  I guess.  Sorry I am a bit of a hack.  

I did find using Postman to be a huge timesaver for getting the calls working.  Once I had calls working in Postman it was super easy to copy the JSON requests into my php application and str_replace the parameters that needed to change.   It was also fantastic to be able to see what the responses looked like in Postman.  Definitely a Postman fan after that project.

**Comment by mindfulsoftware** [comment]
Hi Guys

Thanks for your feedback on this.  I have now added a section on [using the bearer token](/mindfulsoftware/myFastway.ApiClient/wiki/Principles꞉-Authentication#using-the-bearer-token)
