### ISSUE TITLE
on-forwarding response data available?

### ISSUE THREAD

**Issue by Bulmer** [mindfulsoftware/myFastway.ApiClient#13]
In the older api.fastway response data  indicated whether the consignment would be on-forwarded to another courier for final delivery. I checked whether response data "delivery_rf_deeded" value was false. Would that data be possible to include in this new API?

**Comment by Bulmer** [comment]
Any chance of a response to this?

**Comment by mindfulsoftware** [comment]
the Serviced By endpoint under [Addresses](https://github.com/mindfulsoftware/myFastway.ApiClient/wiki/Endpoints%EA%9E%89-Addresses) will tell you if an address is on-forwarded or not.

I realise this means multiple calls to the API which may not be ideal

For changes to the API, its best to go through you Account Manager who will forward to the Project Team.  The Project Team schedule and prioritize all the development work

**Comment by mindfulsoftware** [comment]
LEA is our on-forwarding franchise/solution. If you send a parcel to the address in question it will arrive there.
