### ISSUE TITLE
Status of Consignments

### ISSUE THREAD

**Issue by PatelVish** [mindfulsoftware/myFastway.ApiClient#14]
Is there a way to know the status of consignment, ie whether it is still open/yet to be processed vs processed and ready to be closed?

**Comment by mindfulsoftware** [comment]
The status of a consignment can be derived from the [Track](/mindfulsoftware/myFastway.ApiClient/wiki/Endpoints%EA%9E%89-Track) endpoint.

No scans means the consignment is pending
Any scan means the courier has handled the parcel, its considered in-progress at this point
A SIG or YES status indicates that the parcel has been delivered
