### ISSUE TITLE
addresses/serviced-by is returning incorrect data

### ISSUE THREAD

**Issue by Bulmer** [mindfulsoftware/myFastway.ApiClient#18]
The serviced-by endpoint is now giving responses with false data. For example, an address which is clearly not serviced by Aramex/Fastway returns "{"data":{"deeded":true,"rf":"LEA","cf":"","zone":"SD1","subDepot":""}}".
"deeded" should be false and as far as I know, there is no "LEA" franchise?? I have no alternative but to take the Aramex option off my website until this is sorted. Please advise.

**Comment by mindfulsoftware** [comment]
LEA is our on-forwarding franchise/solution.  If you send a parcel to the address in question it will arrive there.
