### ISSUE TITLE
can I use Curl instead?

### ISSUE THREAD

**Issue by Bulmer** [mindfulsoftware/myFastway.ApiClient#2]
Do I have to use ASP.NET for Authentication to access the MyFastway API or can I use PHP?  Thanks.

**Comment by ChannelSix** [comment]
You can certainly use Curl!

To get an access token:

`curl -d "grant_type=client_credentials&scope=fw-fl2-api-au&client_id=<your client id>&client_secret=<your client secret>" https://identity.fastway.org/connect/token`

(Note that NZ clients should use `scope=fw-fl2-api-nz` in the above call).

This will return a response with the body something like:
`{"access_token":"eyJhbGciOiJSUzI1Ni....","expires_in":3600,"token_type":"Bearer"}`

You can then access the myFastway API adding the access token to the header of each call:

`curl -H "Authorization: Bearer eyJhbGciOiJSUzI1Ni...." https://api.myfastway.com.au/api/consignments/deleted-reasons`

(Note that NZ clients should use `https://api.myfastway.co.nz/api/consignments/deleted-reasons` in the above call).

**Comment by Bulmer** [comment]
Thanks ChannelSix, all good now.

**Comment by AnilDurugkar** [comment]
Thanks for your curl answer, useful for me.
