### ISSUE TITLE
/api/addresses/serviced-by 

### ISSUE THREAD

**Issue by youbet1980** [mindfulsoftware/myFastway.ApiClient#3]
I do not know what "fromRF" is or where I get this.
/api/addresses/serviced-by
`{
  "fromRF": "",
  "locality": "",
  "postalCode": "",
  "lat": 0,
  "lng": 0
}`
I used 
/api/addresses/validate

and I tried using placeId, addressId, hash for the fromRF but in all cases I get the error message
`{"errors":[{"code":"PSC_NF","message":"Sorry, we don't appear to have a service available for the selected locality (WOOLLOONGABBA 4102)"}],"type":2}`
or if I leave fromRF blank I get 
`{"errors":[{"code":"VAL_REQ","path":"FromRF","message":"The FromRF field is required."}]}`

What I am wanting to do is put in a full address and know if fastways will drive a van to the front door and leave a parcel rather than not delivering because the address is too far away or too rural for them to drive to the front door.

**Comment by youbet1980** [comment]
Ok I have found out that "fromRF" is the Franchise location that you are sending from.

I found a list of franchise locations by going to the fastways website
https://www.fastway.com.au/
and viewing the source code of their dropdown box
<img width="378" alt="Screen Shot 2019-03-14 at 1 05 51 pm" src="https://user-images.githubusercontent.com/48540186/54328524-f3555400-4659-11e9-9568-58646bb1fa5b.png">

I am assuming that fastways is finding the delivery depot and then drawing a circle around that depot and if the lat and lng that you provide falls within that circle then they service it.

I am not sure why they need the franchise that you are sending the parcel from to calculate this.

If anyone wanted to fill me in with details I would appreciate it.

**Comment by youbet1980** [comment]
Regarding Serviced By

Here are the results from 2 addresses in the same suburb.
Address 1: Out in the sticks
`{"data":{"deeded":true,"rf":"NTH","cf":"","zone":"ON4","subDepot":""}}`
Address 2: In town
`{"data":{"deeded":true,"rf":"NTH","cf":"","zone":"NTH","subDepot":""}}`

So for the first result I am assuming that ON4 stands for Onforwarding or something.

So when sending it first goes to rf ( assuming Regional Franchise )
Then it is the zone that delivers it. 

Does anybody clarify what cf, rf, zone, subDepot mean and give examples how you know if the customer will actually get it delivered to their door or if fastways will just leave it at a depot and ring up the customer to drive 30+ km's to come and pick up the parcel?

**Comment by mindfulsoftware** [comment]
Thanks for the feedback.  I have now updated the ServicedBy Documentation and added the [Franchise Codes](/mindfulsoftware/myFastway.ApiClient/wiki/Franchise-Codes).  In a future release will will provide an endpoint to query your from RF (Regional Franchise).

Where the delivery is into an onforward area (e.g. ON1, ON2 etc), Fastway are arranging the delivery via an onforward agent, however a delivery to door is still expected. There are situations where service cycles are limited and the final mile delivery agent or Fastway may contact the receiver to see if they want to arrange collection from a township etc to get it quicker, however delivery to door is still the standard Fastway service
