### ISSUE TITLE
400 Response - invalid_scope using http client for AU

### ISSUE THREAD

**Issue by ashermiddleton** [mindfulsoftware/myFastway.ApiClient#31]
Hi,

I'm trying to obtain an oauth token with no success. I've double checked my client and secret from `https://myfastway.com.au/#/admin/api-keys/list`. I'm using a .http file and PHPStorm's http client to make the request. Are the [docs](https://github.com/mindfulsoftware/myFastway.ApiClient/wiki/Principles%EA%9E%89-Authentication) incorrect or am I doing something wrong?

Relevant details:
**http file**:
```
### Aramex Oauth Token
POST https://identity.aramexconnect.com.au/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&
client_id=REDACTED&
client_secret=REDACTED&
scope=ac-api-au
```
**request**:
```
POST https://identity.aramexconnect.com.au/connect/token
Content-Type: application/x-www-form-urlencoded
Content-Length: 137
User-Agent: IntelliJ HTTP Client/PhpStorm 2024.2.0.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
x-http2-scheme: https

grant_type=client_credentials&client_id=REDACTED&client_secret=REDACTED&scope=ac-api-au
```
**response**:
```
HTTP/2 400 Bad Request
cache-control: no-store, no-cache, max-age=0
pragma: no-cache
content-type: application/json; charset=UTF-8
server: Microsoft-IIS/10.0
x-powered-by: ASP.NET
date: Wed, 28 Aug 2024 01:43:21 GMT
x-http2-stream-id: 3
transfer-encoding: chunked

{
  "error": "invalid_scope"
}
```

**Comment by mindfulsoftware** [comment]
Are you able to create a new API key with the description '4583CCCC-4616-4F54-B40A-CE7E8D79ACEE' ?

That way I will be able to identify your account and see if its an account related issue.

**Comment by ashermiddleton** [comment]
> Are you able to create a new API key with the description '4583CCCC-4616-4F54-B40A-CE7E8D79ACEE' ?

Done. Tried with the new id/secret and the request fails with the same error.

**Comment by mindfulsoftware** [comment]
Try again with the new API Key

**Comment by ashermiddleton** [comment]
> Try again with the new API Key

That's working now, thank you. Was something done wrong on my end?

**Comment by mindfulsoftware** [comment]
No, we are currently in the middle of a product rebrand, moving from myFastway to aramexConnect domains

I suspect you logged into myfastway.com.au and created an api key, which is used for api.myfastway.com.au with the scope fw-fl2-api-au.  you then tried to us this token with api.aramexConnect.com.au which expects ac-api-au.

We are redirecting all traffic to aramexConnect this Saturday, which should resolve this

**Comment by mindfulsoftware** [comment]
aramexConnect.com.au is currently up now though, and should work with your current username / password

**Comment by ashermiddleton** [comment]
> No, we are currently in the middle of a product rebrand, moving from myFastway to aramexConnect domains
> 
> I suspect you logged into myfastway.com.au and created an api key, which is used for api.myfastway.com.au with the scope fw-fl2-api-au. you then tried to us this token with api.aramexConnect.com.au which expects ac-api-au.
> 
> We are redirecting all traffic to aramexConnect this Saturday, which should resolve this

You're correct in the assumption that my API key was created on the myfastway domain, thanks for the info.
