### ISSUE TITLE
How do you select the service as ATL

### ISSUE THREAD

**Issue by youbet1980** [mindfulsoftware/myFastway.ApiClient#4]
When doing a query for consignment services here:
https://github.com/mindfulsoftware/myFastway.ApiClient/wiki/Consignment-Services
I get this:
`{
  "data": [
    {
      "code": "DELOPT",
      "name": "Delivery Options",
      "description": "Delivery Options",
      "chargeLevel": "I",
      "items": [
        {
          "code": "ATL",
          "description": "If address is unattended, parcel will be left in a safe place where available",
          "price": 0
        },
        {
          "code": "SIG",
          "description": "Standard Fastway Couriers Delivery",
          "price": 0
        }
      ]
    }
  ]
}`

I would like to create a consignment and use ATL.

ON the consignment page:
https://github.com/mindfulsoftware/myFastway.ApiClient/wiki/Consignments

The json you send has no where to enter "ATL" and instead returns  "Standard Fastway Couriers Delivery"

`{"data":{"price":25.45,"tax":2.545,"total":27.995,"items":[{"productType":"Labels","description":"S: Parcel of 5.00kg dead, 7.29kg cubic (90cm x 18cm x 18cm)","quantity":1,"price":25.45,"tax":2.545,"total":27.995},{"productType":"Service","description":"Standard Fastway Couriers Delivery","quantity":1,"price":0,"tax":0,"total":0}]}}`

Where do I enter the service that I would like to use as ATL? This would ensure that it is never dropped off at a parcel collect and always delivered to the customers door?

**Comment by ChannelSix** [comment]
The project has been updated with a test for adding a service to a consignment.
Essentially the consignment model has a services collection which has two properties: 

- ServiceCode: the code of the service you are selecting (in your example it would be 'DELOPT')
- ServiceItemCode: the code of the service item in the selected service you wish to select (in your example it would either be 'ATL' or 'SIG'

So when posting a consignment, you would use it something like:
```json
{
  "To": {
    "ContactCode": "",
    "BusinessName": "",
    "ContactName": "",
    ...
    }
  },
  "Items": [
    {
      "Quantity": 0,
      "Reference": "",
      "PackageType": "P",
      ...
    },
  ],
  "Services": [
    {
      "ServiceCode": "DELOPT",
      "ServiceItemCode": "SIG"
    }
  ]
}
```

**Comment by youbet1980** [comment]
Thanks this is great I will give this a go.
