### ISSUE TITLE
need more infomation for send a request

### ISSUE THREAD

**Issue by hainuo** [mindfulsoftware/myFastway.ApiClient#7]
i found that the request's params and method is ambiguously in the wiki pages when i used in php  ,how can i got the params for make a request?

**Comment by ChannelSix** [comment]
There are some (albeit brief) [samples provided in a previous issue for Curl](https://github.com/mindfulsoftware/myFastway.ApiClient/issues/2) samples provided in a previous issue for Curl, is this enough to get you started?

**Comment by hainuo** [comment]
i have got it. now i try send the request using A Content-Type header of application/json 
thanks a lot.
