### ISSUE TITLE
the status & scan type of track

### ISSUE THREAD

**Issue by hainuo** [mindfulsoftware/myFastway.ApiClient#8]
when i used trac api , i have some questions.Can you please priovde the courier description for below question?
1. scan type
 how many scan type do you have and what are they?how many scan type description do you have and what are they?
2. status
 what is status? and how many code do you have?how many scan type description do you have and what are they?

**Comment by mindfulsoftware** [comment]
Hi, I have added the [Scan Types](/mindfulsoftware/myFastway.ApiClient/wiki/Codes%EA%9E%89-Scan-Types) most common types of  [Scan Codes](/mindfulsoftware/myFastway.ApiClient/wiki/Codes%EA%9E%89-Scan-Codes) that can be associated with a consignment item.
